/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true,
    paths: {
        Ext: '.',
        App1: './app/',
        App2: '../app2/app/'
    }
});

Ext.application({
    requires: [
        'App2.model.App2Model',
        'App2.store.App2Store1',
        'App2.store.App2Store2'
    ],

    models: [
        'App1Model'
    ],
    stores: [
        'App1Store1',
        'App1Store2'
    ],
    name: 'App1',

    launch: function() {
        var app2Model = Ext.create("App2.model.App2Model", {field1:"value1", field2:"value2", field3:"value3"});
        var app2Store1 = Ext.create("App2.store.App2Store1");
        app2Store1.add(app2Model);
        app2Store1.getCount();
        var app2Store2 = Ext.create("App2.store.App2Store2");
        var storeWithApp2Model = Ext.create('App1.store.App1Store2', {model: 'App2.model.App2Model'});
        console.log("App1 - created test models and stores");
    }

});
