/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true,
    paths: {
        Ext: '.',
        App1: '../app1/app/',
        App2: './app/'
    }
});

Ext.application({
    models: [
        'App2Model',
        'App1Model'
    ],
    stores: [
        'App2Store1',
        'App2Store2',
        'App2Store3'
    ],
    name: 'App2',

    launch: function() {
        var app1Model = Ext.create("App1.model.App1Model");
        var app1Store1 = Ext.create("App1.store.App1Store1");
        var app1Store2 = Ext.create("App1.store.App1Store2");
        var importedModel = Ext.create("App2.model.App1Model");
        var storeWithApp1Model = Ext.create('App2.store.App2Store3', {model: 'App1.model.App1Model'});
        console.log("App2 - created test models and stores");
    }

});
