/*
 * File: app/store/App1Store1.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App1.store.App1Store1', {
    extend: 'Ext.data.Store',
    requires: [
        'App1.model.App1Model'
    ],

    config: {
        model: 'App1.model.App1Model',
        storeId: 'App1Store1'
    }
});